server:
  port: 8087
spring:
  application:
    name: lingxi-shop-user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lingxi
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.26.33
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.26.33
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: shop.lingxi.user.pojo